# Generated by Django 5.1 on 2024-10-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuadro', '0005_rename_id_serie_subserie_serie'),
        ('portada', '0007_alter_portada_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('num_consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripsion', models.CharField(max_length=250)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portada.portada')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.series')),
            ],
        ),
    ]
