# Generated by Django 5.1 on 2024-10-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0007_alter_subserie_serie'),
        ('inventario', '0002_inventario_estatus'),
        ('portada', '0007_alter_portada_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portada.portada'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series'),
        ),
    ]
