# Generated by Django 5.1.1 on 2024-09-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='fecha_creacion',
        ),
    ]
