# Generated by Django 5.1.1 on 2024-09-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0004_series_id_seccion'),
        ('ficha_tecnica', '0003_alter_fichatecnica_id_subserie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='id_seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.seccion'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='id_serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.series'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='id_subserie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.subserie'),
        ),
    ]
