# Generated by Django 5.1 on 2024-10-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0007_alter_subserie_serie'),
        ('ficha_tecnica', '0004_alter_fichatecnica_id_seccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='id_seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.seccion'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='id_serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='id_subserie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.subserie'),
        ),
    ]
