# Generated by Django 5.1.1 on 2024-09-26 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuadro', '0004_series_id_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('catalogo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('archivo_tramite', models.DateField()),
                ('archivo_concentracion', models.DateField()),
                ('baja', models.BooleanField(db_comment='destino del expedinete')),
                ('historico', models.BooleanField(db_comment='destino del expediente')),
                ('reservado', models.BooleanField(db_comment='tipo de acceso')),
                ('publico', models.BooleanField(db_comment='tipo de acceso')),
                ('confidencial', models.BooleanField(db_comment='tipo de acceso')),
                ('contable_fiscal', models.BooleanField(db_column='contable/fiscal', db_comment='valores documentales')),
                ('administrativo', models.BooleanField(db_comment='valores documentales')),
                ('legal', models.BooleanField(db_comment='valores documentales')),
                ('observaciones', models.CharField(blank=True, db_column='observaciones ', max_length=250, null=True)),
                ('id_seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.seccion')),
                ('id_serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.series')),
                ('id_subserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.subserie')),
            ],
        ),
    ]
