# Generated by Django 5.1 on 2024-10-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_delete_catalogo'),
        ('cuadro', '0005_rename_id_serie_subserie_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('catalogo', models.CharField(max_length=50)),
                ('archivo_tramite', models.DateField()),
                ('archivo_concentracion', models.DateField()),
                ('destino_expe', models.CharField(default='valor_por_defecto', max_length=150)),
                ('type_access', models.CharField(default='valor_por_defecto', max_length=150)),
                ('valores_documentales', models.CharField(default='valor_por_defecto', max_length=150)),
                ('observaciones', models.CharField(blank=True, db_column='observaciones ', max_length=250, null=True)),
                ('id_seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.seccion')),
                ('id_serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.series')),
                ('id_subserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.subserie')),
            ],
        ),
    ]
