# Generated by Django 5.1 on 2024-10-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='destino_expe',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='type_access',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='valores_docu',
            fields=[
                ('id_valores', models.AutoField(primary_key=True, serialize=False)),
                ('valores', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='destino_expe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.destino_expe'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='type_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.type_access'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='valores_documentales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.valores_docu'),
        ),
    ]
