# Generated by Django 5.1 on 2024-10-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_destino_expe_type_access_valores_docu_and_more'),
        ('cuadro', '0007_alter_subserie_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='archivo_concentracion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='archivo_tramite',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='destino_expe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.destino_expe'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='id_seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.seccion'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='id_serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='id_subserie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.subserie'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='type_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.type_access'),
        ),
    ]
