# Generated by Django 5.1 on 2024-10-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0005_rename_id_serie_subserie_serie'),
        ('guia', '0001_initial'),
        ('portada', '0007_alter_portada_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiadocu',
            name='num_expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portada.portada'),
        ),
        migrations.AddField(
            model_name='guiadocu',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.seccion'),
        ),
    ]
