# Generated by Django 5.1 on 2024-10-16 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_guiadocu_num_expediente_guiadocu_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadocu',
            name='volumen',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
