# Generated by Django 5.1 on 2024-10-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_alter_guiadocu_volumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadocu',
            name='volumen',
            field=models.IntegerField(),
        ),
    ]
