# Generated by Django 5.1.1 on 2024-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id_serie', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('codigo_serie', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubSerie',
            fields=[
                ('SubSerie', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
