# Generated by Django 5.1 on 2024-10-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0005_rename_id_serie_subserie_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='id_seccion',
            field=models.ForeignKey(blank=True, db_column='seccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.seccion'),
        ),
    ]
