# Generated by Django 5.1 on 2024-10-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0006_alter_series_id_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subserie',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series'),
        ),
    ]
