# Generated by Django 5.1.1 on 2024-09-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuadro', '0004_series_id_seccion'),
        ('ficha_tecnica', '0004_alter_fichatecnica_id_seccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='portada',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('num_expedieente', models.CharField(max_length=150)),
                ('asunto', models.CharField(max_length=150)),
                ('num_legajos', models.PositiveBigIntegerField(default=0)),
                ('num_fojas', models.PositiveBigIntegerField(default=0)),
                ('valores_secundarios', models.CharField(max_length=150)),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(null=True)),
                ('archivo_tramite', models.CharField(max_length=50)),
                ('archivo_concentracio', models.CharField(max_length=50)),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.seccion')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.series')),
                ('soporte_docu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ficha_tecnica.fichatecnica')),
                ('subserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuadro.subserie')),
            ],
        ),
    ]
