# Generated by Django 5.1.1 on 2024-09-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portada',
            name='soporte_docu',
            field=models.CharField(max_length=150),
        ),
    ]
