# Generated by Django 5.1.1 on 2024-09-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0002_alter_portada_soporte_docu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portada',
            old_name='archivo_concentracio',
            new_name='archivo_concentracion',
        ),
        migrations.RenameField(
            model_name='portada',
            old_name='num_expedieente',
            new_name='num_expediente',
        ),
    ]
