# Generated by Django 5.1 on 2024-09-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_tecnica', '0004_alter_fichatecnica_id_seccion_and_more'),
        ('portada', '0003_rename_archivo_concentracio_portada_archivo_concentracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portada',
            name='soporte_docu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ficha_tecnica.fichatecnica'),
        ),
    ]
