# Generated by Django 5.1 on 2024-09-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0004_alter_portada_soporte_docu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portada',
            old_name='soporte_docu',
            new_name='ficha',
        ),
    ]
