# Generated by Django 5.1 on 2024-10-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_destino_expe_type_access_valores_docu_and_more'),
        ('portada', '0005_rename_soporte_docu_portada_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.catalogo'),
        ),
    ]
