# Generated by Django 5.1 on 2024-10-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_catalogo_archivo_concentracion_and_more'),
        ('cuadro', '0007_alter_subserie_serie'),
        ('ficha_tecnica', '0005_alter_fichatecnica_id_seccion_and_more'),
        ('portada', '0007_alter_portada_catalogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portada',
            name='archivo_concentracion',
        ),
        migrations.RemoveField(
            model_name='portada',
            name='archivo_tramite',
        ),
        migrations.AlterField(
            model_name='portada',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogo'),
        ),
        migrations.AlterField(
            model_name='portada',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ficha_tecnica.fichatecnica'),
        ),
        migrations.AlterField(
            model_name='portada',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.seccion'),
        ),
        migrations.AlterField(
            model_name='portada',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series'),
        ),
        migrations.AlterField(
            model_name='portada',
            name='subserie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.subserie'),
        ),
        migrations.AlterField(
            model_name='portada',
            name='valores_secundarios',
            field=models.CharField(choices=[('informativo', 'Informativo'), ('evidencial', 'Evidencia'), ('testimonial', 'Testimonial')], default='informativo', max_length=15),
        ),
    ]
